const fs = require('fs');
const path = require('path');

const indexPath = path.join(__dirname, 'shop.vitrumgroup.org', 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');

// Order: longest strings first to avoid partial matches
const replacements = [
  // === Assets & brand ===
  ['vitrum-white-logo.svg?v=1775177123&amp;width=600', 'ozkaya-logo-white.png'],
  ['vitrum-white-logo.svg?v=1775177123&amp;width=110 110w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=165 165w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=220 220w', 'ozkaya-logo-white.png 110w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 165w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 220w'],
  ['vitrum-white-logo.svg?v=1775177123&amp;width=1100', 'ozkaya-logo-white.png'],
  ['vitrum-white-logo.svg?v=1775177123&amp;width=50 50w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=100 100w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=150 150w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=200 200w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=300 300w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=400 400w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=550 550w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=800 800w, //shop.vitrumgroup.org/cdn/shop/files/vitrum-white-logo.svg?v=1775177123&amp;width=1100 1100w', 'ozkaya-logo-white.png 50w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 100w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 150w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 200w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 300w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 400w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 550w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 800w, //shop.vitrumgroup.org/cdn/shop/files/ozkaya-logo-white.png 1100w'],
  ['vitrum-white-logo.svg?v=1775177123\\u0026width=500', 'ozkaya-logo-white.png'],
  ['Vitrum_favicon_2025.svg?crop=center&height=32&v=1781006477&width=32', 'ozkaya-favicon.png'],
  ['Vitrum Shop', 'Özkaya Steel'],
  ['VITRUM', 'Özkaya Steel'],
  ['Vitrum', 'Özkaya Steel'],
  ['vitrum_group', 'ozkayasteel'],
  ['vitrumlv.myshopify.com', 'ozkayasteel.myshopify.com'],
  ['www.vitrumgroup.org', '#'],
  ['vitrumgroup.org', 'ozkayasteel.az'],

  // === Meta ===
  ['<html class="js" lang="en">', '<html class="js" lang="az">'],
  ['Professional kitchen, refrigeration and shop equipment &ndash; Özkaya Steel', 'Peşəkar mətbəx avadanlıqları — Özkaya Steel'],
  ['Professional kitchen, refrigeration and shop equipment', 'Peşəkar mətbəx avadanlıqları'],
  ['7,000+ products for professional kitchens, bars and shops. 3,000+ venues delivered, 30 years in the business — plan yours with us.', 'Restoran, otel, kafe, çörək sexi, supermarket və istehsalat müəssisələri üçün yerli istehsal və dünya standartlarına uyğun peşəkar mətbəx avadanlıqları.'],

  // === Long content blocks ===
  ['Some projects need more than what\'s on the shelf. Tell us what you\'re opening: a restaurant, a bar, a production kitchen, a store and our team designs the layout, specs the equipment, builds what has to be custom in our\n                                    own factory, and installs it. One partner, from first drawing to the opening day.', 'Bəzi layihələr rəfdə olanlardan daha çoxunu tələb edir. Bizə nə açdığınızı deyin: restoran, bar, istehsal mətbəxi, mağaza — komandamız planı hazırlayır, avadanlıqları seçir, zavodumuzda fərdi istehsal edir və quraşdırır. Bir tərəfdaş, ilk eskizdən açılış gününə qədər.'],
  ['Some projects need more than what\'s on the shelf. Tell us what you\'re opening: a restaurant, a bar, a production kitchen, a store and our team designs the layout, specs the equipment, builds what has to be custom in our own factory, and installs it. One partner, from first drawing to the opening day.', 'Bəzi layihələr rəfdə olanlardan daha çoxunu tələb edir. Bizə nə açdığınızı deyin: restoran, bar, istehsal mətbəxi, mağaza — komandamız planı hazırlayır, avadanlıqları seçir, zavodumuzda fərdi istehsal edir və quraşdırır. Bir tərəfdaş, ilk eskizdən açılış gününə qədər.'],
  ['The brands the industry trusts: Rational, Hobart, Zanussi, ARNEG and more. Chosen, delivered and backed by the team that\'s equipped 5,000+ venues across Europe. Need more than equipment? We design and build whole venues too.', 'Yerli istehsal və Türkiyə idxalı peşəkar mətbəx avadanlıqları. Paslanmayan poladdan fərdi ölçüdə istehsal, layihələndirmə, quraşdırma və servis xidməti. Avadanlıqdan daha çoxuna ehtiyacınız var? Bütün mətbəx həllərini birlikdə həyata keçiririk.'],
  ['Since 1992 we\'ve helped restaurants, bars, kitchens and stores choose the right equipment, fit out their spaces, and keep running long after opening.', 'Uzun illərin təcrübəsinə əsaslanaraq restoranlar, hotellər, kafelər, çörək və şirniyyat sexləri, supermarketlər və istehsalat müəssisələri üçün müasir mətbəx həlləri təqdim edirik.'],
  ['30 years equipping the businesses that feed and serve Europe', 'Azərbaycanda peşəkar mətbəx avadanlıqları istehsalı və layihələndirilməsi'],
  ['Choosing equipment, installation, staff training, warranty and after-service — we cover all of it, not just the sale.', 'Yerli istehsal, layihələndirmə, satış, quraşdırma və servis — avadanlıq satmaq deyil, müəssisənizin işini daha səmərəli və təhlükəsiz edəcək kompleks həllər təqdim edirik.'],
  ['Tell us what you\'re planning: venue type, location, rough timeline, and the right specialist will come back to you. We ship and install across Europe and beyond.', 'Bizə nə planlaşdırdığınızı deyin: obyekt növü, yer, təxmini vaxt — müvafiq mütəxəssis sizinlə əlaqə saxlayacaq. Azərbaycanda və regionda çatdırılma və quraşdırma xidməti.'],
  ['This shop sells to businesses, public bodies and institutions. Our offer is not aimed at consumers.', 'Bu mağaza müəssisələrə, dövlət qurumlarına və institusiyalara satış edir. Təklifimiz fərdi istehlakçılara yönəlməyib.'],
  ['Taxes, discounts and <a href="/policies/shipping-policy">shipping</a> calculated at checkout.', 'Vergilər, endirimlər və <a href="/policies/shipping-policy">çatdırılma</a> sifariş zamanı hesablanır.'],
  ['I agree to the <a href="/policies/terms-of-service" target="_blank" rel="noopener">Terms of service</a> and the <a href="/pages/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a>', 'Razıyam: <a href="/policies/terms-of-service" target="_blank" rel="noopener">Xidmət şərtləri</a> və <a href="/pages/privacy-policy" target="_blank" rel="noopener">Məxfilik siyasəti</a>'],
  ['You must agree to continue to checkout.', 'Sifarişi rəsmiləşdirmək üçün razılıq verməlisiniz.'],
  ['Choosing a selection results in a full page refresh.', 'Seçim edildikdə səhifə yenilənir.'],
  ['Opens in a new window.', 'Yeni pəncərədə açılır.'],
  ['There was an error while updating your cart. Please try again.', 'Səbət yenilənərkən xəta baş verdi. Zəhmət olmasa, yenidən cəhd edin.'],
  ['You can only add [quantity] of this item to your cart.', 'Səbətə yalnız [quantity] ədəd əlavə edə bilərsiniz.'],
  ['Include your country code, e.g. +371 26 123 456', 'Ölkə kodunu daxil edin, məs: +994 50 123 45 67'],

  // === Reviews ===
  ['Mego has been collaborating with Özkaya Steel for many years. Our cooperation is based on key principles: efficiency, professionalism, and reliability.', 'Mego illərdir Özkaya Steel ilə əməkdaşlıq edir. Əməkdaşlığımız əsas prinsiplərə əsaslanır: səmərəlilik, peşəkarlıq və etibarlılıq.'],
  ['The partnership with Özkaya Steel is characterized by strict adherence to agreements, attention to detail, and readiness for effective solutions. These qualities ensure our collaboration is predictable and productive. We value their professionalism and appreciate our long-term partnership.', 'Özkaya Steel ilə tərəfdaşlıq razılaşmalara sadiqlik, detallara diqqət və effektiv həllərə hazır olmaqla xarakterizə olunur. Bu keyfiyyətlər əməkdaşlığımızı proqnozlaşdırılan və məhsuldar edir. Peşəkarlıqlarını qiymətləndiririk və uzunmüddətli tərəfdaşlığımızı yüksək qiymətləndiririk.'],
  ['Director of Growth, Mego Supermarkets', 'İnkişaf direktoru, Mego Supermarketlər'],
  ['In more than 10 years working with Özkaya Steel, I\'ve come to see them not just as a supplier but as a trusted partner', 'Özkaya Steel ilə 10 ildən artıq işləyərkən onları yalnız təchizatçı deyil, etibarlı tərəfdaş kimi görürəm'],
  ['What sets Özkaya Steel apart is their personalized approach. Every project is handled with meticulous attention to detail. They are always ready to assist, offer solutions, and promptly respond to questions.', 'Özkaya Steel-i fərqləndirən fərdi yanaşmadır. Hər layihəyə detallara diqqətlə yanaşılır. Həmişə kömək etməyə, həllər təklif etməyə və suallara tez cavab verməyə hazırdırlar.'],
  ['Head Chef, TheCatch restaurants family', 'Baş aşpaz, TheCatch restoranlar ailəsi'],
  ['Our partner, Özkaya Steel, has proven to be a reliable and professional supplier of retail equipment.', 'Tərəfdaşımız Özkaya Steel etibarlı və peşəkar pərakəndə avadanlıqları təchizatçısı olduğunu sübut etdi.'],
  ['They consistently provide us with modern, high-quality solutions that fully meet the demands of next-generation supermarkets. We greatly value their professionalism, punctuality, and meticulous approach at every stage — from selecting equipment to installation and after-sales support.', 'Bizə müasir, yüksək keyfiyyətli həllər təqdim edirlər ki, bu da yeni nəsil supermarketlərin tələblərini tam ödəyir. Peşəkarlıqlarını, vaxtında çatdırılmanı və hər mərhələdə diqqətli yanaşmanı — avadanlıq seçimindən quraşdırmaya və satış sonrası dəstəyə qədər — yüksək qiymətləndiririk.'],
  ['Technical Director, Sky Supermarkets', 'Texniki direktor, Sky Supermarketlər'],

  // === Collection captions (truncated originals) ===
  ['A good bar runs on more than good bartenders. From cocktail stations', 'Yaxşı bar yalnız yaxşı barmenlərdən asılı deyil. Kokteyl stansiyalarından'],
  ['A wash-up area that keeps pace with the pass is the difference', 'Pass tempinə uyğun qabyuyan sahəsi fərq yaradır'],
  ['A well-built buffet does the selling for you — guests decide with', 'Yaxşı qurulmuş bufet sizin üçün satış edir — qonaqlar qərar verir'],
  ['Reliable cold storage is the backbone of every kitchen, shop and bar', 'Etibarlı soyuducu saxlama hər mətbəx, mağaza və barın təməlidir'],
  ['Every fast kitchen stands on an organised back room: when shelving, racks', 'Hər sürətli mətbəx təşkil olunmuş arxa otağa dayanır: rəflər, stellajlar'],
  ['Guests judge a room before the first plate arrives. This collection covers', 'Qonaqlar ilk boşqab gəlməzdən otağı qiymətləndirir. Bu kolleksiya əhatə edir'],
  ['Good bars run on choreography, and the equipment is half the cast.', 'Yaxşı barlar xoreoqrafiyaya əsaslanır və avadanlıq castın yarısıdır.'],
  ['Cafés live on rhythm — the morning rush, the lunchtime turnover, the', 'Kafelər ritmə yaşayır — səhər tələsi, günorta dövriyyəsi,'],
  ['Bakeries run on a schedule most of the city never sees, and', 'Çörək sexləri şəhərin çox vaxt görmədiyi cədvələ əsaslanır və'],
  ['A pizzeria stands or falls on its oven — but service runs', 'Pizzeriya sobaya görə qalxır və ya düşür — amma xidmət davam edir'],

  // === Product names ===
  ['Heated Food Display Showcase, 97 L, +30/+90°C', 'İsti qida vitrinası, 97 L, +30/+90°C'],
  ['Saro Heated Food Display Showcase NIKLAS, 97L, +30/+90°C', 'Saro isti qida vitrinası NIKLAS, 97L, +30/+90°C'],
  ['Heated showcase SARO NIKLAS', 'Saro NIKLAS isti vitrina'],
  ['CroftMet Electric Stove with Cabinet PES704R, 2 Burners, 5.2 kW', 'CroftMet elektrik sobası, kabinetli PES704R, 2 gözlü, 5.2 kW'],
  ['CroftMet Electric Stove with Right Cabinet PES712R, 6-Burner, 15.6 kW', 'CroftMet elektrik sobası, sağ kabinetli PES712R, 6 gözlü, 15.6 kW'],
  ['CroftMet Electric Floor Stove with Cabinet PES708S, 4 Burners, 10.4 kW', 'CroftMet döşəmə elektrik sobası, kabinetli PES708S, 4 gözlü, 10.4 kW'],
  ['Classic Slot Toaster, 6 Slots, 240 Slices/hr, 3 kW', 'Klassik slot toster, 6 yuvə, 240 dilim/saat, 3 kW'],
  ['Dualit Classic Toaster 6 slots', 'Dualit klassik toster 6 yuvə'],

  // === Stats multicolumn ===
  ['<strong>30+</strong><br/>years experience', '<strong>Uzun</strong><br/>illərin təcrübəsi'],
  ['turning visions into thriving spaces', 'viziyaları uğurlu məkanlara çeviririk'],
  ['<strong>5000+</strong><br/>projects', '<strong>Yerli</strong><br/>istehsal'],
  ['across 20 countries for businesses of all sizes ', 'paslanmayan poladdan fərdi ölçüdə istehsal'],
  ['<strong>15,000</strong> sq. meters', '<strong>Açar</strong> təslim'],
  ['of in-house manufacturing for total quality control', 'quraşdırma və tam keyfiyyət nəzarəti'],
  ['<strong>360</strong>° support', '<strong>360</strong>° dəstək'],
  ['from design through installation - and beyond', 'layihələndirmədən quraşdırmaya və sonrasına qədər'],

  // === Menu - longest first ===
  ['Insulated GN carriers &amp; thermoboxes', 'İzolyasiyalı GN daşıyıcılar və termoboxlar'],
  ['Insulated GN carriers & thermoboxes', 'İzolyasiyalı GN daşıyıcılar və termoboxlar'],
  ['Refrigeration accessories &amp; spares', 'Soyuducu aksesuarları və ehtiyat hissələri'],
  ['Refrigeration accessories & spares', 'Soyuducu aksesuarları və ehtiyat hissələri'],
  ['Food prep machine accessories', 'Qida hazırlama avadanlığı aksesuarları'],
  ['Outdoor sofas &amp; modular seating', 'Açıq hava divanları və modul oturacaqlar'],
  ['Outdoor sofas & modular seating', 'Açıq hava divanları və modul oturacaqlar'],
  ['Weather-resistant table tops', 'Hava şəraitinə davamlı masa üstləri'],
  ['Ice cream &amp; gelato freezers', 'Dondurma və gelato soyuducuları'],
  ['Ice cream & gelato freezers', 'Dondurma və gelato soyuducuları'],
  ['Ice cream dipping cabinets', 'Dondurma vitrin soyuducuları'],
  ['Blast chillers &amp; shock freezers', 'Şok soyuducular və blast çillerlər'],
  ['Blast chillers & shock freezers', 'Şok soyuducular və blast çillerlər'],
  ['Undercounter &amp; worktop', 'Alt dolab və iş səthli'],
  ['Undercounter & worktop', 'Alt dolab və iş səthli'],
  ['Refrigerated workbenches', 'Soyuducu iş masaları'],
  ['Freezer workbenches', 'Dondurucu iş masaları'],
  ['Beer fridges &amp; bottle coolers', 'Pivə soyuducuları və şüşə soyuducuları'],
  ['Beer fridges & bottle coolers', 'Pivə soyuducuları və şüşə soyuduları'],
  ['Multi-decks &amp; wall cases', 'Multi-deck və divar vitrinləri'],
  ['Multi-decks & wall cases', 'Multi-deck və divar vitrinləri'],
  ['Glass-door merchandisers', 'Şüşə qapılı vitrin soyuducuları'],
  ['Pastry &amp; cake display', 'Konditoriya və tort vitrinləri'],
  ['Pastry & cake display', 'Konditoriya və tort vitrinləri'],
  ['Cold room shelving', 'Soyuducu kamera rəfləri'],
  ['Cold room doors', 'Soyuducu kamera qapıları'],
  ['Cold room panels', 'Soyuducu kamera panelləri'],
  ['Refrigeration units', 'Soyuducu avadanlıqları'],
  ['Chiller cold rooms', 'Soyuducu kameralar'],
  ['Freezer rooms', 'Dondurucu kameralar'],
  ['Contact &amp; Panini grills', 'Kontakt və panini qrilər'],
  ['Contact & Panini grills', 'Kontakt və panini qrilər'],
  ['Griddles &amp; Planchas', 'Plancha və qril plitələr'],
  ['Griddles & Planchas', 'Plancha və qril plitələr'],
  ['Salamander grills', 'Salamander qrilər'],
  ['Kebab &amp; Shawarma grills', 'Kabab və şaurma qriləri'],
  ['Kebab & Shawarma grills', 'Kabab və şaurma qriləri'],
  ['Chicken rotisseries', 'Toyuq rotisseriləri'],
  ['Roller grills &amp; Hot dogs', 'Roller qril və hot-dog avadanlıqları'],
  ['Roller grills & Hot dogs', 'Roller qril və hot-dog avadanlıqları'],
  ['Street food counters &amp; carts', 'Küçə yeməyi stendləri və arabalari'],
  ['Street food counters & carts', 'Küçə yeməyi stendləri və arabalari'],
  ['Electric deck ovens', 'Elektrik deck sobaları'],
  ['Gas deck ovens', 'Qaz deck sobaları'],
  ['Conveyor pizza ovens', 'Konveyer pizza sobaları'],
  ['Wood-fired &amp; Hybrid', 'Odun və hibrid sobalar'],
  ['Wood-fired & Hybrid', 'Odun və hibrid sobalar'],
  ['Dough &amp; flour processing', 'Xəmir və un emalı'],
  ['Dough & flour processing', 'Xəmir və un emalı'],
  ['High-speed ovens', 'Sürətli sobalar'],
  ['Microwave ovens', 'Mikrodalğalı sobalar'],
  ['Bakery ovens', 'Çörək sexi sobaları'],
  ['Combi &amp; convection', 'Kombi və konveksiya'],
  ['Combi & convection', 'Kombi və konveksiya'],
  ['Food processors', 'Qida emalı avadanlıqları'],
  ['Meat processing', 'Ət emalı'],
  ['Work tables &amp; Counters', 'İş masaları və stendlər'],
  ['Work tables & Counters', 'İş masaları və stendlər'],
  ['Neutral workbenches', 'Neytral iş masaları'],
  ['Commercial shelving', 'Peşəkar rəflər'],
  ['Wire shelving', 'Tel rəflər'],
  ['Polymer shelving', 'Polimer rəflər'],
  ['Heavy-duty industrial', 'Ağır sənaye stellajları'],
  ['Specialty racks', 'Xüsusi stellajlar'],
  ['Carts &amp; Trolleys', 'Araba və trolleylər'],
  ['Carts & Trolleys', 'Araba və trolleylər'],
  ['Lockers &amp; Wardrobes', 'Şkaflar və dolablar'],
  ['Lockers & Wardrobes', 'Şkaflar və dolablar'],
  ['Cups, mugs &amp; saucers', 'Fincanlar, stəkanlar və nəlbəklər'],
  ['Cups, mugs & saucers', 'Fincanlar, stəkanlar və nəlbəklər'],
  ['Espresso cups', 'Espresso fincanları'],
  ['Serving dishes &amp; platters', 'Servis qabları və boşqablar'],
  ['Serving dishes & platters', 'Servis qabları və boşqablar'],
  ['Jugs &amp; carafes', 'Qrafin və karafalar'],
  ['Jugs & carafes', 'Qrafin və karafalar'],
  ['Egg cups', 'Yumurta qabları'],
  ['Cutlery &amp; Flatware', 'Çatal-bıçaq dəstləri'],
  ['Cutlery & Flatware', 'Çatal-bıçaq dəstləri'],
  ['Table forks', 'Masaya çatal'],
  ['Table knives', 'Masaya bıçaq'],
  ['Table spoons', 'Masaya qaşıq'],
  ['Dessert cutlery', 'Desert çatal-bıçaqları'],
  ['Coffee &amp; tea spoons', 'Kofe və çay qaşıqları'],
  ['Coffee & tea spoons', 'Kofe və çay qaşıqları'],
  ['Steak knives', 'Steyk bıçaqları'],
  ['Serving cutlery', 'Servis çatal-bıçaqları'],
  ['Serving trays', 'Servis trayləri'],
  ['Salt &amp; pepper mills', 'Duz və bibər dəyirmanları'],
  ['Salt & pepper mills', 'Duz və bibər dəyirmanları'],
  ['Menages &amp; shakers', 'Menaj və shakerlər'],
  ['Menages & shakers', 'Menaj və shakerlər'],
  ['Menu &amp; table signage', 'Menyu və masa nişanları'],
  ['Menu & table signage', 'Menyu və masa nişanları'],
  ['Candle holders', 'Şamdanlar'],
  ['Decorative lighting', 'Dekorativ işıqlandırma'],
  ['Chafing dishes', 'Chafing qabları'],
  ['Display cabinet inserts', 'Vitrin insertləri'],
  ['Display risers &amp; stands', 'Vitrin stendləri və riserlər'],
  ['Display risers & stands', 'Vitrin stendləri və riserlər'],
  ['Display risers &amp; Stands', 'Vitrin stendləri və riserlər'],
  ['Display risers & Stands', 'Vitrin stendləri və riserlər'],
  ['Display baskets', 'Vitrin səbətləri'],
  ['Bread baskets', 'Çörək səbətləri'],
  ['Food covers', 'Qida qapaqları'],
  ['Buffet stations', 'Bufet stansiyaları'],
  ['Salad bars', 'Salat barları'],
  ['Heat lamps', 'İsti lampalar'],
  ['Cold display', 'Soyuq vitrin'],
  ['Frying pans &amp; sauté pans', 'Tava və sauté tavaları'],
  ['Frying pans & sauté pans', 'Tava və sauté tavaları'],
  ['Saucepans &amp; casseroles', 'Qazan və kaserol'],
  ['Saucepans & casseroles', 'Qazan və kaserol'],
  ['Stockpots &amp; boiling pots', 'Böyük qazanlar'],
  ['Stockpots & boiling pots', 'Böyük qazanlar'],
  ['Specialty cookware', 'Xüsusi bişirmə qabları'],
  ['Cookware lids', 'Qab qapaqları'],
  ['Roasting pans', 'Qovurma qabları'],
  ['Knives &amp; cutting', 'Bıçaqlar və kəsmə'],
  ['Knives & cutting', 'Bıçaqlar və kəsmə'],
  ['Chef knives', 'Aşpaz bıçaqları'],
  ['Specialty knives', 'Xüsusi bıçaqlar'],
  ['Cutting boards', 'Kəsmə taxtaları'],
  ['Sharpening &amp; knife care', 'Itiləmə və bıçaq qayğısı'],
  ['Sharpening & knife care', 'Itiləmə və bıçaq qayğısı'],
  ['Kitchen utensils &amp; tools', 'Mətbəx ləvazimatları və alətlər'],
  ['Kitchen utensils & tools', 'Mətbəx ləvazimatları və alətlər'],
  ['Ladles &amp; servers', 'Kepçə və servis qabları'],
  ['Ladles & servers', 'Kepçə və servis qabları'],
  ['Spatulas &amp; turners', 'Spatula və çeviricilər'],
  ['Spatulas & turners', 'Spatula və çeviricilər'],
  ['Peelers &amp; graters', 'Tərəvəz soyucular və rəndelər'],
  ['Peelers & graters', 'Tərəvəz soyucular və rəndelər'],
  ['Sieves &amp; colanders', 'Süzgəclər və kolanderlər'],
  ['Sieves & colanders', 'Süzgəclər və kolanderlər'],
  ['Bowls &amp; measuring', 'Qablar və ölçü alətləri'],
  ['Bowls & measuring', 'Qablar və ölçü alətləri'],
  ['Mixing bowls', 'Qarışdırma qabları'],
  ['Measuring &amp; thermometers', 'Ölçü alətləri və termometrlər'],
  ['Measuring & thermometers', 'Ölçü alətləri və termometrlər'],
  ['Pizza &amp; Pastry', 'Pizza və konditoriya'],
  ['Pizza & Pastry', 'Pizza və konditoriya'],
  ['Pizza peels', 'Pizza spatula'],
  ['Pizza pans &amp; screens', 'Pizza qabları və ekranlar'],
  ['Pizza pans & screens', 'Pizza qabları və ekranlar'],
  ['Dough &amp; pastry tools', 'Xəmir və konditor alətləri'],
  ['Dough & pastry tools', 'Xəmir və konditor alətləri'],
  ['Baking trays &amp; moulds', 'Qabyuvan trayləri və formalar'],
  ['Baking trays & moulds', 'Qabyuvan trayləri və formalar'],
  ['Food storage &amp; transport', 'Qida saxlama və daşınma'],
  ['Food storage & transport', 'Qida saxlama və daşınma'],
  ['Gastronorm containers &amp; pans', 'Gastronorm konteynerlər və qablar'],
  ['Gastronorm containers & pans', 'Gastronorm konteynerlər və qablar'],
  ['Storage containers', 'Saxlama konteynerləri'],
  ['GN lids &amp; covers', 'GN qapaqları'],
  ['GN lids & covers', 'GN qapaqları'],
  ['Perforated GN containers', 'Dəlikli GN konteynerlər'],
  ['Food thermoses &amp; transport cans', 'Qida termosları və daşıma qabları'],
  ['Food thermoses & transport cans', 'Qida termosları və daşıma qabları'],
  ['GN accessories', 'GN aksesuarları'],
  ['Insulated delivery bags', 'İzolyasiyalı çatdırılma çantaları'],
  ['Dining furniture', 'Yemək otağı mebeli'],
  ['Dining chairs', 'Yemək stulları'],
  ['Dining tables', 'Yemək masaları'],
  ['Table bases', 'Masa ayaqları'],
  ['Table tops', 'Masa üstləri'],
  ['Bar furniture', 'Bar mebeli'],
  ['Lounge &amp; Soft seating', 'Lounge və yumşaq oturacaqlar'],
  ['Lounge & Soft seating', 'Lounge və yumşaq oturacaqlar'],
  ['Outdoor &amp; terrace furniture', 'Açıq hava və terras mebeli'],
  ['Outdoor & terrace furniture', 'Açıq hava və terras mebeli'],
  ['Outdoor chairs &amp; armchairs', 'Açıq hava stulları və kreslolar'],
  ['Outdoor chairs & armchairs', 'Açıq hava stulları və kreslolar'],
  ['Outdoor tables', 'Açıq hava masaları'],
  ['Outdoor lounge sets', 'Açıq hava lounge dəstləri'],
  ['Sun loungers &amp; sunbeds', 'Günəş şezlongları'],
  ['Sun loungers & sunbeds', 'Günəş şezlongları'],
  ['Outdoor bar stools', 'Açıq hava bar stulları'],
  ['Outdoor table bases', 'Açıq hava masa ayaqları'],
  ['Patio heaters', 'Terras qızdırıcıları'],
  ['Dishwashing tables', 'Qabyuyan masaları'],
  ['Sinks &amp; Pre-rinse', 'Moykalar və ilkin yuyulma'],
  ['Sinks & Pre-rinse', 'Moykalar və ilkin yuyulma'],
  ['Waste &amp; Grease', 'Tullantı və yağ tutucular'],
  ['Waste & Grease', 'Tullantı və yağ tutucular'],
  ['Janitorial &amp; Cleaning', 'Təmizlik avadanlıqları'],
  ['Janitorial & Cleaning', 'Təmizlik avadanlıqları'],
  ['Hygiene &amp; Sanitation', 'Gigiyena və sanitariya'],
  ['Hygiene & Sanitation', 'Gigiyena və sanitariya'],
  ['Bain Marie &amp; Food warmers', 'Bain Marie və qida isidiciləri'],
  ['Bain Marie & Food warmers', 'Bain Marie və qida isidiciləri'],
  ['Heated cabinets', 'İsti dolablar'],
  ['Plate warmers', 'Boşqab isidiciləri'],
  ['Hot display cases', 'İsti vitrinlər'],
  ['Özkaya Steel bar systems', 'Bar sistemləri'],
  ['Vitrum bar systems', 'Bar sistemləri'],
  ['Signature systems', 'İmza sistemlər'],
  ['Cocktail stations', 'Kokteyl stansiyaları'],
  ['Modular back bars', 'Modul arxa barlar'],
  ['Drinks &amp; Draft units', 'İçki və draft avadanlıqları'],
  ['Drinks & Draft units', 'İçki və draft avadanlıqları'],
  ['Coffee bar modules', 'Kofe bar modulları'],
  ['Glasswasher modules', 'Bardaq yuyan modullar'],
  ['Cashier modules', 'Kassa modulları'],
  ['Mobile bars', 'Mobil barlar'],
  ['Cocktail trolleys', 'Kokteyl arabalari'],
  ['Ice maker machines', 'Buz maşınları'],
  ['Underbar ice bins &amp; Crushers', 'Alt bar buz qutuları və crusherlər'],
  ['Underbar ice bins & Crushers', 'Alt bar buz qutuları və crusherlər'],
  ['Ice buckets &amp; Tools', 'Buz qabları və alətlər'],
  ['Ice buckets & Tools', 'Buz qabları və alətlər'],
  ['Drink preparation', 'İçki hazırlama'],
  ['Beverage dispensing', 'İçki paylayıcıları'],
  ['Draft &amp; Tap systems', 'Draft və kran sistemləri'],
  ['Draft & Tap systems', 'Draft və kran sistemləri'],
  ['Glasswashing', 'Bardaq yuyulması'],
  ['Bartending tools', 'Barmen alətləri'],
  ['Bar glassware', 'Bar şüşə qabları'],
  ['Cocktail glasses', 'Kokteyl stəkanları'],
  ['Wine glasses', 'Şərab stəkanları'],
  ['Beer glasses', 'Pivə stəkanları'],
  ['Champagne flutes', 'Şampan stəkanları'],
  ['Spirit &amp; Shot glasses', 'Spirt və shot stəkanları'],
  ['Spirit & Shot glasses', 'Spirt və shot stəkanları'],
  ['Espresso equipment', 'Espresso avadanlıqları'],
  ['Espresso machines', 'Espresso maşınları'],
  ['Espresso grinders', 'Espresso dəyirmanları'],
  ['Tampers &amp; Knock boxes', 'Tamper və knock boxlar'],
  ['Tampers & Knock boxes', 'Tamper və knock boxlar'],
  ['Filter &amp; Bulk coffee', 'Filter və bulk kofe'],
  ['Filter & Bulk coffee', 'Filter və bulk kofe'],
  ['Drink dispensers', 'İçki dispenserləri'],
  ['Café accessories', 'Kafe aksesuarları'],
  ['Ice Cream &amp; Frozen', 'Dondurma və dondurulmuş'],
  ['Ice Cream & Frozen', 'Dondurma və dondurulmuş'],
  ['Soft-serve machines', 'Soft-serve maşınları'],
  ['Batch freezers', 'Partiya dondurucuları'],
  ['Pasteurisers &amp; Accessories', 'Pastörizatorlar və aksesuarlar'],
  ['Pasteurisers & Accessories', 'Pastörizatorlar və aksesuarlar'],
  ['Gondola shelving', 'Gondola rəfləri'],
  ['Slatwall systems', 'Slatwall sistemləri'],
  ['Gridwall systems', 'Gridwall sistemləri'],
  ['Pegboard systems', 'Pegboard sistemləri'],
  ['Wall uprights &amp; Brackets', 'Divar stoykaları və konsollar'],
  ['Wall uprights & Brackets', 'Divar stoykaları və konsollar'],
  ['Display cases &amp; Showcases', 'Vitrin və showcase-lər'],
  ['Display cases & Showcases', 'Vitrin və showcase-lər'],
  ['Mannequins &amp; Forms', 'Manekenlər və formalar'],
  ['Mannequins & Forms', 'Manekenlər və formalar'],
  ['Garment racks &amp; Hangers', 'Geyim stellajları və asqılar'],
  ['Garment racks & Hangers', 'Geyim stellajları və asqılar'],
  ['Hooks &amp; Merchandising', 'Qarmaqlar və merchandising'],
  ['Hooks & Merchandising', 'Qarmaqlar və merchandising'],
  ['Baskets &amp; Trolleys', 'Səbətlər və arabalari'],
  ['Baskets & Trolleys', 'Səbətlər və arabalari'],
  ['Fitting rooms', 'Geyinmə otaqları'],
  ['Tables &amp; Plinths', 'Masalar və plintlər'],
  ['Tables & Plinths', 'Masalar və plintlər'],
  ['Signs &amp; Holders', 'Nişanlar və tutacaqlar'],
  ['Signs & Holders', 'Nişanlar və tutacaqlar'],
  ['Shelf-edge &amp; Ticketing', 'Rəf kənarı və etiketlər'],
  ['Shelf-edge & Ticketing', 'Rəf kənarı və etiketlər'],
  ['Writable &amp; Digital', 'Yazıla bilən və rəqəmsal'],
  ['Writable & Digital', 'Yazıla bilən və rəqəmsal'],
  ['Cash desks &amp; Counters', 'Kassa masaları və stendlər'],
  ['Cash desks & Counters', 'Kassa masaları və stendlər'],
  ['Queue management', 'Növbə idarəetməsi'],
  ['POS hardware mounts', 'POS avadanlığı montajları'],
  ['Wall-mount hoods', 'Divar montajlı havalandırma'],
  ['Island hoods', 'Ada tipli havalandırma'],
  ['Condensate hoods', 'Kondensat havalandırması'],
  ['Make-up air hoods', 'Make-up air havalandırması'],
  ['Grease filters &amp; Accessories', 'Yağ filtrləri və aksesuarlar'],
  ['Grease filters & Accessories', 'Yağ filtrləri və aksesuarlar'],
  ['Ductwork &amp; Fans', 'Kanallar və ventilyatorlar'],
  ['Ductwork & Fans', 'Kanallar və ventilyatorlar'],
  ['Laundry equipment', 'Cərrahlaşdırma avadanlıqları'],
  ['Textiles &amp; Linens', 'Tekstil və dəsmal'],
  ['Textiles & Linens', 'Tekstil və dəsmal'],
  ['Gift packaging', 'Hədiyyə qablaşdırması'],
  ['Protective packaging', 'Qoruyucu qablaşdırma'],
  ['Labels &amp; stickers', 'Etiketlər və stikerlər'],
  ['Labels & stickers', 'Etiketlər və stikerlər'],
  ['Tapes &amp; dispensers', 'Lentlər və dispenserlər'],
  ['Tapes & dispensers', 'Lentlər və dispenserlər'],
  ['Till rolls &amp; receipt paper', 'Kassa lenti və çek kağızı'],
  ['Till rolls & receipt paper', 'Kassa lenti və çek kağızı'],
  ['Food wrapping papers', 'Qida büküm kağızları'],
  ['Carrier bags', 'Daşıma çantaları'],
  ['Fast food &amp; QSR', 'Fast-food və QSR'],
  ['Fast food & QSR', 'Fast-food və QSR'],
  ['Kebab &amp; Shawarma', 'Kabab və şaurma'],
  ['Kebab & Shawarma', 'Kabab və şaurma'],
  ['Bar &amp; Pub', 'Bar və pub'],
  ['Bar & Pub', 'Bar və pub'],
  ['Wine shop', 'Şərab mağazası'],
  ['Supermarket &amp; Grocery', 'Supermarket və ərzaq'],
  ['Supermarket & Grocery', 'Supermarket və ərzaq'],
  ['Convenience &amp; Fuel', 'Kiçik market və yanacaq'],
  ['Convenience & Fuel', 'Kiçik market və yanacaq'],
  ['Specialty retail', 'Xüsusi pərakəndə'],
  ['Fashion &amp; Boutique', 'Moda və butik'],
  ['Fashion & Boutique', 'Moda və butik'],
  ['Catering şirkətləri', 'Katerinq şirkətləri'],
  ['Dishwashing &amp; hygiene', 'Qabyuyan və gigiyena'],
  ['Dishwashing & hygiene', 'Qabyuyan və gigiyena'],
  ['Dishwashing &amp; Hygiene', 'Qabyuyan və gigiyena'],
  ['Dishwashing & Hygiene', 'Qabyuyan və gigiyena'],
  ['Buffet &amp; food display', 'Bufet və qida vitrini'],
  ['Buffet & food display', 'Bufet və qida vitrini'],
  ['Hot holding &amp; warming', 'İsti saxlama və isitmə'],
  ['Hot holding & warming', 'İsti saxlama və isitmə'],
  ['Kitchenware &amp; knives', 'Mətbəx ləvazimatları və bıçaqlar'],
  ['Kitchenware & knives', 'Mətbəx ləvazimatları və bıçaqlar'],
  ['Tableware &amp; bar', 'Qab-qacaq və bar'],
  ['Tableware & bar', 'Qab-qacaq və bar'],
  ['Storage &amp; worktables', 'Saxlama və iş masaları'],
  ['Storage & worktables', 'Saxlama və iş masaları'],
  ['Food preparation', 'Qida hazırlığı'],
  ['Ovens &amp; bakery', 'Sobalar və çörək sexi'],
  ['Ovens & bakery', 'Sobalar və çörək sexi'],
  ['Cooking equipment', 'Bişirmə avadanlığı'],
  ['Shop fittings', 'Mağaza avadanlıqları'],
  ['Signage &amp; POS', 'Nişanlar və POS'],
  ['Signage & POS', 'Nişanlar və POS'],
  ['Laundry &amp; textiles', 'Cərrahlaşdırma və tekstil'],
  ['Laundry & textiles', 'Cərrahlaşdırma və tekstil'],
  ['Packaging &amp; supplies', 'Qablaşdırma və ləvazimatlar'],
  ['Packaging & supplies', 'Qablaşdırma və ləvazimatlar'],
  ['Coffee &amp; café', 'Kofe və kafe'],
  ['Coffee & café', 'Kofe və kafe'],
  ['Bar &amp; beverage', 'Bar və içki'],
  ['Bar & beverage', 'Bar və içki'],
  ['Bar &amp; Beverage', 'Bar və içki'],
  ['Bar & Beverage', 'Bar və içki'],
  ['Furniture &amp; terrace', 'Mebel və terras'],
  ['Furniture & terrace', 'Mebel və terras'],
  ['Fridges &amp; freezers', 'Soyuducular və dondurucular'],
  ['Fridges & freezers', 'Soyuducular və dondurucular'],
  ['Uprights &amp; reach-ins', 'Şkaf tipli soyuducular'],
  ['Uprights & reach-ins', 'Şkaf tipli soyuducular'],
  ['Chest freezers', 'Sandıq dondurucular'],
  ['Prep refrigeration', 'Hazırlıq soyuducuları'],
  ['Prep tables', 'Hazırlıq masaları'],
  ['Display refrigeration', 'Vitrin soyuducuları'],
  ['Serve-over counters', 'Serve-over stendlər'],
  ['Freezer islands', 'Dondurucu adalar'],
  ['Countertop display', 'Stolüstü vitrin'],
  ['Display freezers', 'Vitrin dondurucuları'],
  ['Refrigerated islands', 'Soyuducu adalar'],
  ['Cold rooms', 'Soyuducu kameralar'],
  ['Ranges &amp; cookers', 'Plitələr və sobalar'],
  ['Ranges & cookers', 'Plitələr və sobalar'],
  ['Grills &amp; griddles', 'Qril və plitələr'],
  ['Grills & griddles', 'Qril və plitələr'],
  ['Chargrills', 'Közləmə qriləri'],
  ['Pasta &amp; boiling', 'Makaron və qaynatma'],
  ['Pasta & boiling', 'Makaron və qaynatma'],
  ['Specialty cooking', 'Xüsusi bişirmə'],
  ['Food prep machines', 'Qida hazırlama maşınları'],
  ['Shelving systems', 'Rəf sistemləri'],
  ['Plates &amp; Bowls', 'Boşqab və kaseler'],
  ['Plates & Bowls', 'Boşqab və kaseler'],
  ['Pizza ovens', 'Pizza sobaları'],
  ['Workbenches', 'İş masaları'],
  ['Cookware', 'Bişirmə qabları'],
  ['Refrigeration', 'Soyuducu avadanlığı'],
  ['Ventilation', 'Havalandırma'],
  ['Dishwashers', 'Qabyuyan maşınlar'],
  ['Categories', 'Kateqoriyalar'],
  ['Business type', 'Biznes növü'],
  ['Search products', 'Məhsul axtar'],
  ['Search 5,000+ products', '5000+ məhsul axtar'],
  ['Clear search term', 'Axtarışı təmizlə'],
  ['Skip to content', 'Məzmuna keç'],
  ['Enquiry list', 'Sorğu siyahısı'],
  ['Log in', 'Daxil ol'],
  ['Log in to check out faster.', 'Daha sürətli sifariş üçün daxil olun.'],
  ['Have an account?', 'Hesabınız var?'],
  ['Language', 'Dil'],
  ['English', 'Azərbaycan'],
  ['View all', 'Hamısına bax'],
  ['Popular categories', 'Populyar kateqoriyalar'],
  ['Browse by business type', 'Biznes növünə görə bax'],
  ['Shop by category', 'Kateqoriyaya görə alış-veriş'],
  ['Shop by business type', 'Biznes növünə görə alış-veriş'],
  ['Professional equipment for kitchens, bars and retail spaces', 'Mətbəx, bar və pərakəndə məkanlar üçün peşəkar avadanlıq'],
  ['Opening something? We do the whole room, not just the equipment.', 'Bir şey açırsınız? Yalnız avadanlıq deyil, bütün otağı həyata keçiririk.'],
  ['Request a design consultation', 'Dizayn məsləhəti tələb et'],
  ['Learn more about us', 'Haqqımızda ətraflı'],
  ['Featured brands', 'Seçilmiş brendlər'],
  ['Have a bigger or more complex project?', 'Daha böyük və ya mürəkkəb layihəniz var?'],
  ['Full name *', 'Ad soyad *'],
  ['Company name *', 'Şirkət adı *'],
  ['Email *', 'E-poçt *'],
  ['Phone', 'Telefon'],
  ['Country', 'Ölkə'],
  ['Comment', 'Şərh'],
  ['Send enquiry', 'Sorğu göndər'],
  ['Customer reviews carousel', 'Müştəri rəyləri karuseli'],
  ['Reviews carousel', 'Rəylər karuseli'],
  ['Previous review', 'Əvvəlki rəy'],
  ['Next review', 'Növbəti rəy'],
  ['Review', 'Rəy'],
  ['Sale', 'Endirim'],
  ['Add to enquiry list', 'Sorğu siyahısına əlavə et'],
  ['Add to cart', 'Səbətə əlavə et'],
  ['Saved!', 'Saxlanıldı!'],
  ['Sold out', 'Satılıb'],
  ['Unavailable', 'Mövcud deyil'],
  ['Vendor:', 'İstehsalçı:'],
  ['Regular price', 'Adi qiymət'],
  ['Sale price', 'Endirim qiyməti'],
  ['Your cart', 'Səbətiniz'],
  ['Your cart is empty', 'Səbətiniz boşdur'],
  ['Continue shopping', 'Alış-verişə davam et'],
  ['Loading...', 'Yüklənir...'],
  ['Subtotal', 'Ara cəmi'],
  ['Proceed to checkout', 'Sifarişi rəsmiləşdir'],
  ['Close', 'Bağla'],
  ['Menu', 'Menyu'],
  ['Search', 'Axtar'],
  ['Cart', 'Səbət'],
  ['Subscribe', 'Abunə ol'],
  ['Quick links', 'Sürətli keçidlər'],
  ['Catalog', 'Kataloq'],
  ['About us', 'Haqqımızda'],
  ['Portfolio', 'Portfolio'],
  ['Privacy Policy', 'Məxfilik siyasəti'],
  ['Terms &amp; Conditions', 'Şərtlər və qaydalar'],
  ['Terms & Conditions', 'Şərtlər və qaydalar'],
  ['Cookies Policy', 'Kukilər siyasəti'],
  ['Delivery &amp; Payment', 'Çatdırılma və ödəniş'],
  ['Delivery & Payment', 'Çatdırılma və ödəniş'],
  ['Returns &amp; Withdrawals', 'Qaytarma və imtina'],
  ['Returns & Withdrawals', 'Qaytarma və imtina'],
  ['Legal notice', 'Hüquqi bildiriş'],
  ['Credentials', 'Əlaqə'],
  ['Contact us', 'Bizimlə əlaqə'],
  ['Subscribe to our emails', 'E-poçtumuza abunə olun'],
  ['Payment methods', 'Ödəniş üsulları'],
  ['Copyright &copy; 2026 Özkaya Steel. All rights reserved.', 'Copyright &copy; 2026 Özkaya Steel. Bütün hüquqlar qorunur.'],
  ['{{ count }} item', '{{ count }} məhsul'],
  ['{{ count }} items', '{{ count }} məhsul'],
  ['0 items', '0 məhsul'],
  ['HoReCa', 'HoReCa'],
  ['Retail', 'Pərakəndə'],
  ['Restaurant', 'Restoran'],
  ['Café', 'Kafe'],
  ['Hotel', 'Otel'],
  ['Pizzeria', 'Pizzeriya'],
  ['Bakery', 'Çörək sexi'],
  ['Catering', 'Katerinq'],
  ['Furniture', 'Mebel'],
  ['Mixers', 'Mikserlər'],
  ['Blenders', 'Blenderlər'],
  ['Fryers', 'Fritöz'],
  ['Toasters', 'Tosterlər'],
  ['Minibars', 'Minibarlar'],
  ['Ashtrays', 'Külqabları'],
  ['Whisks', 'Çırpıcılar'],
  ['Tongs', 'Maşa'],
  ['Crockery', 'Qab-qacaq'],
  ['Plates', 'Boşqablar'],
  ['Bowls', 'Kaseler'],
  ['Mugs', 'Stəkanlar'],
  ['Workwear', 'İş geyimi'],
  ['Catering', 'Katerinq'],
  ['Ice equipment', 'Buz avadanlığı'],
  ['View cart', 'Səbətə bax'],
  ['Protected by hCaptcha', 'hCaptcha ilə qorunur'],
  ['Slider', 'Slayder'],
  ['of', ' / '],
  ['[value] - Unavailable', '[value] - Mövcud deyil'],
  ['[quantity] items added', '[quantity] məhsul əlavə edildi'],
  ['[quantity] item added', '[quantity] məhsul əlavə edildi'],
  ['[quantity] items removed', '[quantity] məhsul silindi'],
  ['[quantity] item removed', '[quantity] məhsul silindi'],
  ['[money]/ea', '[money]/ədəd'],
  ['This item has a minimum of [min]', 'Minimum [min] ədəd'],
  ['This item has a maximum of [max]', 'Maksimum [max] ədəd'],
  ['You can only add this item in increments of [step]', 'Yalnız [step] ədəd artımla əlavə edə bilərsiniz'],
  ['Image [index] is now available in gallery view', 'Şəkil [index] qalereyada mövcuddur'],
  ['Link copied to clipboard', 'Link buferə kopyalandı'],
  ['Pause slideshow', 'Slaydşounu dayandır'],
  ['Play slideshow', 'Slaydşounu oynat'],
  ['Gift card recipient form expanded', 'Hədiyyə kartı forması genişləndirildi'],
  ['Gift card recipient form collapsed', 'Hədiyyə kartı forması yığcamlaşdırıldı'],
  ['[count] countries/regions found', '[count] ölkə/region tapıldı'],
  ['Slide left', 'Sola sürüşdür'],
  ['Slide right', 'Sağa sürüşdür'],
  ['Email', 'E-poçt'],
  ['Fast food', 'Fast-food'],
  ['Shop fittings', 'Mağaza avadanlıqları'],
];

// Footer legal removal
html = html.replace(/<h2 class="footer-block__heading inline-richtext">Credentials<\/h2>\s*<div class="footer-block__details-content rte">\s*<p>Özkaya Steel SIA<\/p>[\s\S]*?<p>Bank account: LV60 RIKO 0002 9303 5554 2<\/p>/,
  '<h2 class="footer-block__heading inline-richtext">Əlaqə</h2>\n                        <div class="footer-block__details-content rte">\n                            <p>Özkaya Steel Pro</p>\n                            <p>Azərbaycan</p>\n                            <p>Yerli istehsal • Layihələndirmə • Satış • Quraşdırma • Servis</p>');

// Also handle if Credentials wasn't translated yet
html = html.replace(/<h2 class="footer-block__heading inline-richtext">Credentials<\/h2>\s*<div class="footer-block__details-content rte">\s*<p>Vitrum Shop SIA<\/p>[\s\S]*?<p>Bank account: LV60 RIKO 0002 9303 5554 2<\/p>/,
  '<h2 class="footer-block__heading inline-richtext">Əlaqə</h2>\n                        <div class="footer-block__details-content rte">\n                            <p>Özkaya Steel Pro</p>\n                            <p>Azərbaycan</p>\n                            <p>Yerli istehsal • Layihələndirmə • Satış • Quraşdırma • Servis</p>');

// Remove Latvian address block if still present
html = html.replace(/<p>Juridiskā adrese: Bitēnu iela 1, Berģi,<\/p>\s*<p>Garkalnes pag\., Ropažu nov\., LV-1024<br\/><br\/>Reg\. Nr\.: LV40003508763<\/p>\s*<p>Bank: Luminor Bank AS<\/p>\s*<p>SWIFT: RIKOLV2X<\/p>\s*<p>Bank account: LV60 RIKO 0002 9303 5554 2<\/p>/g, '');

// Logo alt and dimensions
html = html.replace(/height="38\.47533632286996"/g, 'height="55"');
html = html.replace(/height="78\.69955156950672"/g, 'height="70"');

// CTA link
html = html.replace(/href="https:\/\/www\.#\/about-us"/g, 'href="#contact"');
html = html.replace(/href="https:\/\/www\.#\/all-projects"/g, 'href="#contact"');
html = html.replace(/href="https:\/\/#\/#contact"/g, 'href="#contact"');

// Apply all replacements
for (const [from, to] of replacements) {
  const count = html.split(from).length - 1;
  if (count > 0) {
    html = html.split(from).join(to);
  }
}

fs.writeFileSync(indexPath, html, 'utf8');
console.log('Translation complete. Written to', indexPath);
